### ISSUE TITLE
GSM too small for GGTT

### ISSUE THREAD

**Issue by riastradh** [riastradh/netbsd-src#17]
[  13.4385586] panic: kernel diagnostic assertion "(sizeof(gen6_pte_t) * (ggtt->vm.total >> PAGE_SHIFT) <= ggtt->gsmsz - (sizeof(gen6_pte_t) * ggtt_offset))" failed: file "/.../sys/external/bsd/drm2/dist/drm/i915/gt/gen6_ppgtt.c", line 352 oversize ggtt vm total 80000000 requiring 200000 bytes of ptes, gsm has 840 bytes for ptes

(note: numbers are in hex; assertion updated in 9aa40bc67ab99f25e1dafe91f8480d89e6f5aaa7)

**Comment by chucksilvers** [comment]
(deleted)

**Comment by riastradh** [comment]
fixed in https://github.com/riastradh/netbsd-src/commit/2d2a12a300775ce9e56bd95e764a05b0dd0544e7
