### ISSUE TITLE
Wedged in intel_dp

### ISSUE THREAD

**Issue by riastradh** [riastradh/netbsd-src#18]
intel_dp_compute_config() at netbsd:intel_dp_compute_config+0x2de
intel_ddi_compute_config() at netbsd:intel_ddi_compute_config+0xed
intel_atomic_check() at netbsd:intel_atomic_check+0x1026
intel_modeset_init() at netbsd:intel_modeset_init+0x1607
i915_driver_probe() at netbsd:i915_driver_probe+0x92c
i915drmkms_attach_real() at netbsd:i915drmkms_attach_real+0x88
config_mountroot_thread() at netbsd:config_mountroot_thread+0x60

**Comment by alarixnia** [comment]
This can be closed
