### ISSUE TITLE
amdgpu: missing firmware tear down crashes very strangely

### ISSUE THREAD

**Issue by mrgtwentythree** [riastradh/netbsd-src#26]
testing on a Ryzen 3200G CPU, which has Vega8 / R2 graphics.

without the firmware files present (the "amdgpu/picasso_*" files
from linux-firmware), amdgpu crashes when tearing down the
so-far setup.

unfortunately, this one does not seem to be a simple case of missing
mutex_destroy or other minor tear down, but something confusing.

there are two pci_mapreg_map() calls in amdgpu_device.c, and their
results are stored in the softc-equiv.  the tag, handle, and size that
are returned are then later passed to bus_space_unmap(), in what
seems to be a 100% valid sequence of code _and_ printf() after the
_map() call maps the arguments passed into the _unmap() call.

the problematic mapping is the "rmmio" mapping, not the "rio"
mapping, which is successfully unmapped imediately before the
crash.  it appears that the tag ends up being NULL, as the crash
indicates that this line faults:

    602 bus_space_unmap(bus_space_tag_t t, const bus_space_handle_t bsh,
...
    609         if ((t->bst_exists & BUS_SPACE_OVERRIDE_UNMAP) == 0)

NULL->bst_exists is offset 0x18, and that is the fault address.

these are some of the hand-copied logs i've created.  i only have
pictures of the failures.

mapped rmmio  tag 0xffffffff.81418fa0 handle ffffba02.498f4000 size 80000
gonna unmap:  tag 0xffffffff.81418fa0 handle ffffba02.498f4000 size 80000
uvm_fault(0xffffffff.8141c2e0, 0x0, 1) -> e
trap type 6 code 0 rip 0xffffffff.804489f8 cs 0x8 rflags 0x10286 cr2 0x18 ilevel 0 rsp 0xffffba02.498eaea0
curlwp 0xffffdb25.5fb9e580 pid 0.174 lowest kstack 0xffffba02.498e62c0

(i find it odd that the handle is so close to the stack pointer here.)

having the firmware files present on this machine presents a different
problem i will discuss in a different issue.

**Comment by mrgtwentythree** [comment]
taylor suggest it was the doorbell unmap, and it is.  this gets me to
the issue in #27 instead:

--- a/sys/external/bsd/drm2/dist/drm/amd/amdgpu/amdgpu_device.c
+++ b/sys/external/bsd/drm2/dist/drm/amd/amdgpu/amdgpu_device.c
@@ -816,8 +816,9 @@ static int amdgpu_device_doorbell_init(struct amdgpu_device *adev)
 static void amdgpu_device_doorbell_fini(struct amdgpu_device *adev)
 {
 #ifdef __NetBSD__
-       bus_space_unmap(adev->doorbell.bst, adev->doorbell.bsh,
-           adev->doorbell.num_doorbells * sizeof(u32));
+       if (adev->doorbell.num_doorbells != 0)
+               bus_space_unmap(adev->doorbell.bst, adev->doorbell.bsh,
+                   adev->doorbell.num_doorbells * sizeof(u32));
 #else

**Comment by mrgtwentythree** [comment]
(markdown sure did not like that pasted patch.)

removing the firmware again, with the "if (adev->doorbell.num_doorbells != 0)"
fix applied, causes an instant reset at some point during post mountroot attach.

**Comment by riastradh** [comment]
original problem fixed in 24bf4831f9b265dbb460c1acd927b2197c987d45
