### ISSUE TITLE
amdgpu: ring test fails during attach, system asserts with mutex count error

### ISSUE THREAD

**Issue by mrgtwentythree** [riastradh/netbsd-src#27]
testing on a Ryzen 3200G CPU, which has Vega8 / R2 graphics.

with firmware installed, this system gets further than issue#26.  here is
some more hand-copied info:

amdgpu: warn RAS: ras ta ucode is not available
kern info: [drm] kiq ring mec 2 pipe 1 q 0
amdgpu0 [drm:netbsd:amdgpu_ring_test_helper+0x4a] *ERROR* ring gf test failed (-60)
[drm:netbsd:amdgpu_device_init+0x1fc6] *ERROR* hw_init of IP block <gfx_v9_0> failed -60
amdgpu0: error: amdgpu_device_ip_init failed
kern info: [drm] amdgpu: finished device.
panic: .. "ci>ci_mtx_count == -1" failed: file ".../kern/kern_synch.c", line 724 mi_switch: cpu0: ci_mtx_count (-2) != -1 (block with spin-mutex held) 

so the gfx_v9_0 ring test fails with a timeout (60 = ETIMEDOUT), and
then during teardown we trip this mutex assert.

i'm pretty sure this is because in kern_kthread.c:

kthread_sysinit(void)
...
        mutex_init(&kthread_lock, MUTEX_DEFAULT, IPL_NONE);

kthread_join(lwp_t *l)
...
        mutex_enter(&kthread_lock);

however, there is a spinlock taken at this point:

sched_main.c:

void drm_sched_fini(struct drm_gpu_scheduler *sched)
{
        if (sched->thread) {
                spin_lock(&sched->job_list_lock); 
                kthread_stop(sched->thread);

**Comment by riastradh** [comment]
fixed in c3d49d44733734098721109ccc5e4fb5d3bc4646
