### ISSUE TITLE
amdgpu: drm_sched_fini() hangs forever when driver init fails

### ISSUE THREAD

**Issue by mrgtwentythree** [riastradh/netbsd-src#31]
ryzen 3200G with latest branch no longer spin-lock helds inside
kthread_join() but it now hangs waiting forever.  the last few lines
on the console before hang are (hand copied):

hwmgr_sw_init smu backend is smu10_smu 
powerplay sw init successful
kern info: [drm] Found VCN firmware Version ENC: 1.9 DEC: 1 VEP: 0 Revision: 28
kern info: [drm] PSP loading VCN firmware
kern warning: [drm] psp command (0x5) failed and response status is (0x0)
[drm:netbsd:psp_hw_start+0x337] *ERROR* PSP load tmr failed!
[drm:netbsd:psp_hw_start+0x337] *ERROR* PSP load tmr failed!
[drm:netbsd:amdgpu_device_hw_loading+0xfa] *ERROR* hw_init of IP block <psp> failed: -22
amdgpu0: error: amdgpu_device_ip_init failed
amdgpu0: error: Fatal error during GPU init
kern inf: [drm] amdgpu: finishing device.

from the ddb console i was able to determine that one autoconf
thread is stuck here (and presumably has dv_pending raised
for amdgpu device, waiting for it to create a wsdisplay0):

sleepq_block+0x12c
cv_wait+0x42
kthread_join+0x4c
linux_kthread_stop+0x46
drm_sched_fini+0x1b
amdgpu_fence_driver_fini+0x6b
amdgpu_device_fini+0x6b
amdgpu_device_unload_kms+0x36
amdgpu_device_load_kms+0xd3
drm_dev_register+0x166
amdgpu_attach_real+0xac

**Comment by mrgtwentythree** [comment]
if i am understanding this properly, there are a dozen or so threads all
waiting in 'drmschedw' wchan, so apparently the cv_broadcast() in
linux_kthread_stop() is not waking up this lwp (i believe that the shutdown
wants to cancel all these sched instances).  these are the names of
the threads sitting in 'drmschedw' wchan:

jpeg_dec, vnc_enc1, vnc_enc0, vnc_dec, sdma0, comp_1.3.1,
comp_1.2.1, comp_1.1.1, comp_1.0.1, comp_1.3.0, comp_1.2.0,
comp_1.1.0, comp_1.0.0, and gfx.

**Comment by riastradh** [comment]
kthread changes warrant new stack traces

**Comment by mrgtwentythree** [comment]
this specific problem is fixed.

(now, it crashes when a later problem that shouldn't happen makes the driver try to unload, which fails, and even if it worked, would panic with cnopen: no console.)
