### ISSUE TITLE
BUILD ABORTED.

### ISSUE THREAD

**Issue by Marietto2008** [riastradh/netbsd-src#32]
./build.sh -U -u -j4 -m amd64 -O ~/obj release

/root/obj/tooldir.NetBSD-9.2-amd64/bin/x86_64--netbsd-objcopy -x cprop.o
--- dependall-sys ---
--- dependall-drmkms_linux ---
dependall ===> sys/modules/drmkms_linux
nbmake[7]: nbmake[7]: don't know how to make linux_sg.c. Stop
linux_atomic64.d' is up to date.linux_backlight.d' is up to date.
linux_dma_buf.d' is up to date.linux_dma_fence.d' is up to date.
linux_dma_fence_array.d' is up to date.linux_dma_fence_chain.d' is up to date.
linux_dma_resv.d' is up to date.linux_dmi.d' is up to date.
linux_firmware.d' is up to date.linux_hrtimer.d' is up to date.
linux_i2c.d' is up to date.linux_idr.d' is up to date.
linux_irq_work.d' is up to date.linux_kmap.d' is up to date.
linux_list_sort.d' is up to date.linux_module.d' is up to date.
linux_notifier.d' is up to date.linux_pci.d' is up to date.
linux_radixtree.d' is up to date.linux_rcu.d' is up to date.
linux_rwsem.d' is up to date.linux_sg.c' was not built (being made, type OP_DEPS_FOUND, flags REMAKE|DONE_WAIT|DONE_ALLSRC|DONECYCLE)!
linux_srcu.d' is up to date.linux_stop_machine.d' is up to date.
linux_sync_file.d' is up to date.linux_tasklet.d' is up to date.
linux_wait_bit.d' is up to date.linux_work.d' is up to date.
linux_writecomb.d' is up to date.linux_ww_mutex.d' is up to date.
linux_xa.d' is up to date.afterdepend' was not built (deferred, type OP_DEPENDS|OP_NOTMAIN|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)!
`afterdepend' has .ORDER dependency against .depend (deferred, type OP_DEPENDS|OP_NOPATH|OP_HAS_COMMANDS|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONE_ORDER|CYCLE|DONECYCLE)
nbmake[6]: stopped in /home/mario/Desktop/Dati/netbsd-src/sys/modules
--- dependall-drmkms ---
nbmake[6]: stopped in /home/mario/Desktop/Dati/netbsd-src/sys/modules
--- dependall-drm ---
nbmake[7]: stopped in /home/mario/Desktop/Dati/netbsd-src/sys/modules/drm
--- dependall-compat_linux ---
nbmake[7]: stopped in /home/mario/Desktop/Dati/netbsd-src/sys/modules/compat_linux
--- dependall-compat_linux32 ---
nbmake[7]: stopped in /home/mario/Desktop/Dati/netbsd-src/sys/modules/compat_linux32
--- dependall-external ---
nbmake[8]: stopped in /home/mario/Desktop/Dati/netbsd-src/external/gpl3/gcc/usr.bin
--- dependall-sys ---
--- dependall-compat_linux ---
nbmake[6]: stopped in /home/mario/Desktop/Dati/netbsd-src/sys/modules
--- dependall-drm ---
nbmake[6]: stopped in /home/mario/Desktop/Dati/netbsd-src/sys/modules
--- dependall-compat_linux32 ---
nbmake[6]: stopped in /home/mario/Desktop/Dati/netbsd-src/sys/modules
--- dependall-external ---
nbmake[7]: stopped in /home/mario/Desktop/Dati/netbsd-src/external/gpl3/gcc
nbmake[6]: stopped in /home/mario/Desktop/Dati/netbsd-src/external/gpl3
--- dependall-sys ---
nbmake[5]: stopped in /home/mario/Desktop/Dati/netbsd-src/sys
nbmake[4]: stopped in /home/mario/Desktop/Dati/netbsd-src
--- dependall-external ---
--- dependall-gdb ---
nbmake[9]: stopped in /home/mario/Desktop/Dati/netbsd-src/external/gpl3/gdb/lib/libgdb
nbmake[8]: stopped in /home/mario/Desktop/Dati/netbsd-src/external/gpl3/gdb/lib
nbmake[7]: stopped in /home/mario/Desktop/Dati/netbsd-src/external/gpl3/gdb
nbmake[6]: stopped in /home/mario/Desktop/Dati/netbsd-src/external/gpl3
nbmake[5]: stopped in /home/mario/Desktop/Dati/netbsd-src/external
nbmake[4]: stopped in /home/mario/Desktop/Dati/netbsd-src
nbmake[3]: stopped in /home/mario/Desktop/Dati/netbsd-src
nbmake[2]: stopped in /home/mario/Desktop/Dati/netbsd-src

nbmake[1]: stopped in /home/mario/Desktop/Dati/netbsd-src

nbmake: stopped in /home/mario/Desktop/Dati/netbsd-src

ERROR: Failed to make release
*** BUILD ABORTED ***
netbsd-marietto#

**Comment by riastradh** [comment]
fixed ages ago now
