### ISSUE TITLE
amdgpu: kernel panic with RX580

### ISSUE THREAD

**Issue by vazub** [riastradh/netbsd-src#38]
branch: **reredrm56**
commit: **441f26ecc16568094f947d9d3faf891451e1a697**
custom kernel: 
- GENERIC (with enabled amdgpu and disabled other drm drivers (intel, nvidia, radeon), LOCKDEBUG enabled, 
- ddb.commandonenter=bt;show registers;sync (in sysctl.conf)

crash dump: didn't get any, probably did something wrong to get it? would need further guidance with this.

At this time, can only present these, sorry:
![image](https://user-images.githubusercontent.com/662354/139479996-6474f0df-0e9f-4eaa-8fb6-bffb031df48c.png)
![image](https://user-images.githubusercontent.com/662354/139480029-8c3f25e0-80d8-481f-ab92-5f9cc60b8317.png)

**Comment by mrgtwentythree** [comment]
sw_init of IP block <gmc_v8_0> failed -2

which then leads to no wsdisplay0 attaching, and the panic you see (also see issue#33, which is about how to handle this failure.)

**Comment by vazub** [comment]
It just occurred to me, that I was actually trying the latest code without providing firmware blob manually. I was assuming it would be pulled automatically or something. Will have to retry then.

**Comment by vazub** [comment]
Boots without issues out of re4drm56 branch, with firmware blobs manually copied to /libdata/firmware/amdgpu.

This ticket can be closed.
