### ISSUE TITLE
crash in i915 on kabylake 

### ISSUE THREAD

**Issue by mrgtwentythree** [riastradh/netbsd-src#39]
while moving the mouse this happened:

[ 423287.913217] panic: kernel diagnostic assertion "cv_is_valid(cv)" failed: file "/usr/branches/riastradh-drm/netbsd-src/sys/kern/kern_condvar.c", line 511 
[ 423287.913217] cpu0: Begin traceback...
[ 423287.913217] vpanic() at netbsd:vpanic+0x156
[ 423287.913217] __x86_indirect_thunk_rax() at netbsd:__x86_indirect_thunk_rax
[ 423287.913217] cv_broadcast() at netbsd:cv_broadcast+0x56
[ 423287.913217] linux___dma_fence_signal_wake() at netbsd:linux___dma_fence_signal_wake+0x13e
[ 423287.913217] signal_irq_work() at netbsd:signal_irq_work+0x2ca
[ 423287.913217] irq_work_intr() at netbsd:irq_work_intr+0x87
[ 423287.913217] softint_dispatch() at netbsd:softint_dispatch+0xf2
[ 423287.913217] DDB lost frame for netbsd:Xsoftintr+0x4f, trying 0xffffcf0492d620f0
[ 423287.913217] Xsoftintr() at netbsd:Xsoftintr+0x4f

no X apps were being started or should be exiting.  looks like the cv
was destroyed recently?

(gdb) f 4
#4  0xffffffff80a47b4a in cv_broadcast (cv=0xffffcf04a8544c50) at /usr/branches/riastradh-drm/netbsd-src/sys/kern/kern_condvar.c:511
511             KASSERT(cv_is_valid(cv));
(gdb) p *cv
$2 = {cv_opaque = {0x0, 0xffffffff80fa6ea0 <deadcv>}}

unfortunately, there actual callback happening is lost:

(gdb) f 5
#5  0xffffffff80be0c54 in linux___dma_fence_signal_wake (fence=0xfffff661b98c1380, timestamp=<optimized out>)
    at /usr/branches/riastradh-drm/netbsd-src/sys/external/bsd/drm2/linux/linux_dma_fence.c:1176
1176                    (*fcb->func)(fence, fcb);
(gdb) p fcb
$3 = <optimized out>

as you can tell, i have the core dump.

**Comment by riastradh** [comment]
fixed in i915_request.c 1.17
dup https://gnats.netbsd.org/56561
